name: BitriseClient
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  BitriseClient:
    platform: iOS
    type: application
    sources:
      - BitriseClient
    configFiles:
      Debug: configs/BitriseClient-Debug.xcconfig
      Release: configs/BitriseClient-Release.xcconfig
    dependencies:
      - target: ActionPopoverButton
      - carthage: APIKit
      - carthage: Continuum
      - carthage: Result
      - carthage: TKKeyboardControl
      - carthage: Realm
      - carthage: RealmSwift
  BitriseClientTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - Tests/BitriseClientTests
  ActionPopoverButton:
    platform: iOS
    type: framework
    sources:
      - ActionPopoverButton
    configFiles:
      Debug: configs/ActionPopoverButton-Debug.xcconfig
      Release: configs/ActionPopoverButton-Release.xcconfig
