name: BitriseClient
options:
  minimumXcodeGenVersion: 2.5.0
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  BitriseClient:
    platform: iOS
    type: application
    sources:
      - BitriseClient
      - RxProperty/Sources/RxProperty/RxProperty.swift
    configFiles:
      Debug: configs/BitriseClient-Debug.xcconfig
      Release: configs/BitriseClient-Release.xcconfig
    dependencies:
      - target: ActionPopoverButton
      - target: Core
      - carthage: APIKit
      - carthage: DeepDiff
      - carthage: DifferenceKit
      - carthage: Highlightr
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift
      - carthage: TKKeyboardControl
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES
  BitriseClientTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/BitriseClientTests-Debug.xcconfig
    sources:
      - Tests/
    dependencies:
      - target: BitriseClient
      - target: Core
      - carthage: RxSwift
      - carthage: RxTest
    scheme:
      testTargets:
        - BitriseClientTests
      gatherCoverageData: true
  Core:
    platform: iOS
    type: framework
    sources:
      - Core/
    dependencies:
      - carthage: APIKit
    configFiles:
      Debug: configs/Core.xcconfig
      Release: configs/Core.xcconfig
  ActionPopoverButton:
    platform: iOS
    type: framework
    sources:
      - ActionPopoverButton/ActionPopoverButton
    configFiles:
      Debug: configs/ActionPopoverButton-Debug.xcconfig
      Release: configs/ActionPopoverButton-Release.xcconfig
