name: BitriseClient
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  BitriseClient:
    platform: iOS
    type: application
    sources:
      - BitriseClient
    configFiles:
      Debug: configs/BitriseClient-Debug.xcconfig
      Release: configs/BitriseClient-Release.xcconfig
    dependencies:
      - target: ActionPopoverButton
      - carthage: APIKit
      - carthage: Continuum
      - carthage: DeepDiff
      - carthage: Result
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: TKKeyboardControl
    prebuildScripts:
      - name: sourcery
        script: if [ -z $CI ];then sourcery;fi
  BitriseClientTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/BitriseClientTests-Debug.xcconfig
    sources:
      - Tests/BitriseClientTests
    dependencies:
      - target: BitriseClient
    scheme:
      testTargets:
        - BitriseClientTests
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YESS
          isEnabled: true
  ActionPopoverButton:
    platform: iOS
    type: framework
    sources:
      - ActionPopoverButton
    configFiles:
      Debug: configs/ActionPopoverButton-Debug.xcconfig
      Release: configs/ActionPopoverButton-Release.xcconfig
