name: BitriseClient
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  BitriseClient:
    platform: iOS
    type: application
    sources:
      - BitriseClient
    configFiles:
      Debug: configs/BitriseClient-Debug.xcconfig
      Release: configs/BitriseClient-Release.xcconfig
    dependencies:
      - target: ActionPopoverButton
      - carthage: APIKit
      - carthage: Continuum
      - carthage: Result
      - carthage: TKKeyboardControl
      - carthage: Realm
      - carthage: RealmSwift
    scheme:
      testTargets:
        - BitriseClientTests
      gatherCoverageData: true

  BitriseClientTests:
    platform: iOS
    type: bundle.unit-test
    configFiles:
      Debug: configs/BitriseClientTests-Debug.xcconfig
    sources:
      - Tests/BitriseClientTests
    dependencies:
      - target: BitriseClient
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BitriseClient.app/BitriseClient"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
      OTHER_SWIFT_FLAGS: "$(inherited) -DTEST"
  ActionPopoverButton:
    platform: iOS
    type: framework
    sources:
      - ActionPopoverButton
    configFiles:
      Debug: configs/ActionPopoverButton-Debug.xcconfig
      Release: configs/ActionPopoverButton-Release.xcconfig
