name: BitriseClient-SwiftUI
options:
  minimumXcodeGenVersion: 2.6.0
targets:
  BitriseClient:
    platform: iOS
    type: application
    sources:
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.BitriseClient-SwiftUI
      SUPPORTS_MACCATALYST: YES
      DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: YES
    configFiles:
      Debug: Config/xcconfig/Base.xcconfig
      Release: Config/xcconfig/Base.xcconfig
    dependencies:
      - target: Core
      - target: APIKit
    scheme:
      environmentVariables:
        API_TOKEN: ${API_TOKEN}
  APIKit:
    platform: iOS
    type: framework
    sources:
      - Carthage/Checkouts/APIKit/Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.APIKit
  Core:
    platform: iOS
    type: framework
    sources:
      - Core/
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.BitriseKit
    dependencies:
      - target: APIKit
