name: BitriseClient-SwiftUI
options:
  minimumXcodeGenVersion: 2.7.0
targets:
  BitriseClient:
    platform: iOS
    type: application
    sources:
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.BitriseClient-SwiftUI
      SUPPORTS_MACCATALYST: YES
      DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: YES
    configFiles:
      Debug: Config/xcconfig/Base.xcconfig
      Release: Config/xcconfig/Base.xcconfig
    dependencies:
      - target: Core
    scheme:
      environmentVariables:
        API_TOKEN: ${API_TOKEN}
  Core:
    platform: iOS
    type: framework
    sources:
      - Core/
    dependencies:
      - swiftpm:
        repositoryURL: "https://github.com/ishkawa/APIKit"
        versionRequirement:
          kind: upToNextMajorVersion
          minimumVersion: 5.0.0
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: jp.toshi0383.BitriseKit
